language: generic 

sudo: required
services: 
  - docker

before-install:
 - docker build -t svisagan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true svisagan/docker-react npm run test