sudo: required
services: 
  - docker

before_install:
 - docker build -t svisagan83/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true svisagan83/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-visagan"
  env: "DockerReactVisagan-env"
  bucket_name: "elasticbeanstalk-us-east-1-636402340807"
  bucket_path: "docker-react-visagan"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
